name: check last version
on:
  # push:
  #   branch:
 schedule:
 -  cron: '0 10 * * *'
    
jobs:
  check_version:
    runs-on: ubuntu-22.04
    steps:
      - id: check_version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: home-assistant
          repo: core
          excludes: prerelease, draft

      - name: fail when not matching
        if: steps.check_version.outputs.release != '2022.12.7'
        run: echo "last version "${{ steps.test.check_version.release }}" != '2022.12.7'" && exit 1  

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
