name: release
on:
  push:
    branches: [ main ]
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: home-assistant/core
          ref: 2022.11.4
          path: ha
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: loeken/docker-home-assistant
          path: docker-home-assistant
      - name: ls
        run: cp docker-home-assistant/Dockerfile ha/Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: loeken/home-assistant:latest,loeken/home-assistant:2022.11.0
          context: ./ha
          no-cache: true
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: loeken/home-assistant:latest
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: loeken/home-assistant:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'